import React, { useState } from 'react';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Sparkles, Send, Mic, Wand2 } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { toast } from 'sonner';

const themePresets = [
  { icon: '🎮', label: 'Gaming Night', prompt: 'casual Friday gaming session for the team' },
  { icon: '🍕', label: 'Team Lunch', prompt: 'team lunch with pizza and casual networking' },
  { icon: '🏆', label: 'Awards Night', prompt: 'formal awards ceremony to celebrate team achievements' },
  { icon: '🧘', label: 'Wellness', prompt: 'wellness workshop with meditation and stretching' },
];

export default function AIEventCreationAssistant({ onEventGenerated }) {
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedEvent, setGeneratedEvent] = useState(null);

  const handleGenerate = async (customPrompt = null) => {
    const finalPrompt = customPrompt || prompt;
    if (!finalPrompt.trim()) {
      toast.error('Please describe your event idea');
      return;
    }

    setIsGenerating(true);
    try {
      const response = await base44.functions.invoke('aiEventPlanningAssistant', {
        prompt: finalPrompt,
        user_context: { generating_full_event: true }
      });

      const eventData = response.data;
      setGeneratedEvent(eventData);
      
      if (onEventGenerated) {
        onEventGenerated(eventData);
      }

      toast.success('Event generated by AI!');
    } catch (error) {
      toast.error('Failed to generate event');
      console.error(error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* AI Assistant Hero */}
      <Card className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 border-blue-100 dark:border-blue-800/30 shadow-sm">
        <div className="absolute -top-10 -right-10 w-32 h-32 bg-primary/10 rounded-full blur-2xl" />
        <CardContent className="relative z-10 p-6">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white">
              AI Co-pilot
            </h2>
          </div>
          <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
            Tell us the vibe, and we'll draft the details, suggest activities, and find the perfect theme.
          </p>

          {/* Input Area */}
          <div className="relative">
            <Textarea
              placeholder="e.g., 'Chill Friday gaming session for engineers'"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              className="min-h-[80px] pr-12 text-base"
            />
            <Button
              size="icon"
              onClick={() => handleGenerate()}
              disabled={isGenerating}
              className="absolute bottom-2 right-2 h-9 w-9 rounded-lg bg-primary hover:bg-primary/90"
            >
              {isGenerating ? (
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
              ) : (
                <Send className="w-4 h-4" />
              )}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Theme Presets */}
      <div className="flex gap-2 overflow-x-auto no-scrollbar pb-2">
        {themePresets.map((preset, idx) => (
          <Button
            key={idx}
            variant="outline"
            onClick={() => handleGenerate(preset.prompt)}
            disabled={isGenerating}
            className="flex-shrink-0 rounded-xl bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 hover:border-primary/50"
          >
            <span className="text-lg mr-2">{preset.icon}</span>
            <span className="text-sm font-semibold">{preset.label}</span>
          </Button>
        ))}
      </div>

      {/* Generated Event Preview */}
      {generatedEvent && (
        <Card className="border-2 border-primary/20">
          <CardHeader>
            <div className="flex items-center justify-between">
              <h3 className="font-bold text-slate-900 dark:text-white">
                AI Generated Event
              </h3>
              <Badge className="bg-primary/10 text-primary border-primary/20">
                <Wand2 className="w-3 h-3 mr-1" />
                Auto-saving
              </Badge>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <label className="text-sm font-semibold text-slate-700 dark:text-slate-300">
                Event Name
              </label>
              <Input 
                value={generatedEvent.title || ''} 
                className="mt-1"
                readOnly
              />
            </div>
            <div>
              <label className="text-sm font-semibold text-slate-700 dark:text-slate-300">
                Description
              </label>
              <Textarea 
                value={generatedEvent.description || ''} 
                className="mt-1"
                rows={3}
                readOnly
              />
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}