import React, { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Target, Sparkles } from 'lucide-react';
import { toast } from 'sonner';

export default function CustomChallengeCreator() {
  const queryClient = useQueryClient();
  const [challenge, setChallenge] = useState({
    challenge_name: '',
    description: '',
    target_points: 50,
    duration_days: 7,
    challenge_type: 'individual'
  });

  const createChallengeMutation = useMutation({
    mutationFn: async (data) => {
      return await base44.entities.PersonalChallenge.create({
        ...data,
        status: 'active',
        start_date: new Date().toISOString(),
        end_date: new Date(Date.now() + data.duration_days * 24 * 60 * 60 * 1000).toISOString()
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries(['personal-challenges']);
      toast.success('Challenge created successfully!');
      setChallenge({
        challenge_name: '',
        description: '',
        target_points: 50,
        duration_days: 7,
        challenge_type: 'individual'
      });
    }
  });

  const generateWithAIMutation = useMutation({
    mutationFn: async (goalDescription) => {
      const response = await base44.functions.invoke('aiAdminAssistant', {
        action: 'custom_query',
        query: `Generate a company challenge based on this goal: ${goalDescription}`
      });
      return response;
    },
    onSuccess: (data) => {
      // Parse AI response and populate form
      toast.success('Challenge generated by AI');
    }
  });

  return (
    <Card data-b44-sync="true" data-feature="admin" data-component="customchallengecreator">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Target className="h-5 w-5 text-purple-600" />
          Create Custom Challenge
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="p-4 bg-purple-50 border border-purple-200 rounded-lg">
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="h-4 w-4 text-purple-600" />
            <span className="text-sm font-medium text-purple-900">
              Create challenges tied to your company values and goals
            </span>
          </div>
          <p className="text-xs text-purple-700">
            Examples: "Complete 3 peer recognitions this week" or "Attend 2 wellness events"
          </p>
        </div>

        <div className="space-y-3">
          <div>
            <Label>Challenge Name</Label>
            <Input
              value={challenge.challenge_name}
              onChange={(e) => setChallenge({...challenge, challenge_name: e.target.value})}
              placeholder="e.g., Recognition Champion"
            />
          </div>

          <div>
            <Label>Description</Label>
            <Textarea
              value={challenge.description}
              onChange={(e) => setChallenge({...challenge, description: e.target.value})}
              placeholder="What participants need to do..."
              rows={3}
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label>Points Reward</Label>
              <Input
                type="number"
                value={challenge.target_points}
                onChange={(e) => setChallenge({...challenge, target_points: parseInt(e.target.value)})}
              />
            </div>

            <div>
              <Label>Duration (days)</Label>
              <Input
                type="number"
                value={challenge.duration_days}
                onChange={(e) => setChallenge({...challenge, duration_days: parseInt(e.target.value)})}
              />
            </div>
          </div>

          <div>
            <Label>Challenge Type</Label>
            <Select 
              value={challenge.challenge_type}
              onValueChange={(value) => setChallenge({...challenge, challenge_type: value})}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="individual">Individual</SelectItem>
                <SelectItem value="team">Team-based</SelectItem>
                <SelectItem value="company_wide">Company-wide</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        <div className="flex gap-2">
          <Button
            onClick={() => createChallengeMutation.mutate(challenge)}
            disabled={!challenge.challenge_name || createChallengeMutation.isPending}
            className="flex-1 bg-purple-600 hover:bg-purple-700"
          >
            Create Challenge
          </Button>
          <Button
            variant="outline"
            onClick={() => generateWithAIMutation.mutate(challenge.description)}
            disabled={generateWithAIMutation.isPending}
          >
            <Sparkles className="h-4 w-4" />
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}