/**
 * Entity Type Definitions
 * Centralized TypeScript interfaces for all entities
 * @module types/entities
 */

// Base entity fields (auto-generated by Base44)
export interface BaseEntity {
  id: string;
  created_date: string;
  updated_date: string;
  created_by: string;
}

// User entity (built-in)
export interface User extends BaseEntity {
  full_name: string;
  email: string;
  role: 'admin' | 'user';
  user_type?: 'facilitator' | 'participant';
}

// Activity entity
export interface Activity extends BaseEntity {
  title: string;
  description: string;
  instructions: string;
  type: 'icebreaker' | 'creative' | 'competitive' | 'wellness' | 'learning' | 'social';
  duration: '5-15min' | '15-30min' | '30+min';
  capacity?: number;
  materials_needed?: string;
  image_url?: string;
  popularity_score: number;
  is_template: boolean;
  interaction_type?: string;
  skills_developed?: string[];
  skill_level?: 'beginner' | 'intermediate' | 'advanced';
  learning_outcomes?: string[];
}

// Event entity
export interface Event extends BaseEntity {
  activity_id: string;
  title: string;
  event_type: 'meeting' | 'workshop' | 'training' | 'social' | 'wellness' | 'presentation' | 'brainstorm' | 'other';
  scheduled_date: string;
  duration_minutes?: number;
  status: 'draft' | 'scheduled' | 'in_progress' | 'completed' | 'cancelled' | 'rescheduled';
  magic_link?: string;
  max_participants?: number;
  custom_instructions?: string;
  meeting_link?: string;
  event_format: 'online' | 'offline' | 'hybrid';
  location?: string;
  facilitator_name?: string;
  facilitator_email?: string;
  is_recurring: boolean;
  recurring_series_id?: string;
  points_awarded: number;
  registration_required: boolean;
  waitlist_enabled: boolean;
}

// Participation entity
export interface Participation extends BaseEntity {
  event_id: string;
  participant_name: string;
  participant_email: string;
  rsvp_status: 'yes' | 'no' | 'maybe';
  attended: boolean;
  submission?: {
    type: string;
    content: string;
    file_url?: string;
  };
  engagement_score?: number;
  feedback?: string;
  points_awarded: boolean;
  activity_completed: boolean;
  feedback_submitted: boolean;
  skills_gained?: string[];
}

// UserProfile entity
export interface UserProfile extends BaseEntity {
  user_email: string;
  status: 'active' | 'suspended' | 'pending';
  display_name?: string;
  bio?: string;
  avatar_url?: string;
  department?: string;
  location?: string;
  job_title?: string;
  activity_preferences?: {
    preferred_types?: string[];
    avoid_types?: string[];
    preferred_duration?: string;
    energy_preference?: string;
    group_size_preference?: string;
  };
  notification_preferences?: {
    enabled_channels?: string[];
    event_reminders?: string;
    recognition_notifications?: boolean;
  };
  onboarding_completed: boolean;
}

// UserPoints entity
export interface UserPoints extends BaseEntity {
  user_email: string;
  total_points: number;
  lifetime_points: number;
  current_tier?: string;
  points_this_month: number;
  points_this_week: number;
}

// Badge entity
export interface Badge extends BaseEntity {
  badge_name: string;
  badge_description: string;
  badge_icon: string;
  badge_type: string;
  award_criteria?: {
    type: string;
    threshold?: number;
  };
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
  points_value: number;
  is_active: boolean;
}

// Notification entity
export interface Notification extends BaseEntity {
  user_email: string;
  type: string;
  title: string;
  message: string;
  read: boolean;
  action_url?: string;
  priority: 'low' | 'medium' | 'high';
}

// Team entity
export interface Team extends BaseEntity {
  team_name: string;
  description?: string;
  team_type: 'department' | 'project' | 'interest' | 'custom';
  is_public: boolean;
  member_count: number;
}

// Recognition entity
export interface Recognition extends BaseEntity {
  from_user_email: string;
  to_user_email: string;
  recognition_type: string;
  message: string;
  visibility: 'public' | 'team_only' | 'private';
  points_awarded?: number;
}